<?php
/*------------------------------------------------------------------------
 # SM Slider - Version 1.1
 # Copyright (c) 2013 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

$options = $this->getConfigObject();
$uniqued ='container_slider_'.rand().time();
$smarthelper= Mage::helper('slider/utils');
$list = $this->getProducts();

if(!empty($list)){
	echo $this->getScriptTags();?>
	<?php if(!empty($options->pretext)) { ?>
		<div class="pre-text"><?php echo $options->pretext; ?></div>
	<?php } ?>
	<div id="<?php echo $uniqued; ?>" class="container-slider" style="<?php if( $options->anchor == "bottom" ){ echo "margin-bottom:40px;"; }?>">
			<div class="page-title-slider"><?php echo $options->slider_title_text;?></div>
			<?php if($options->anchor =="top"){?>
			<?php if($options->button_display == 1){?>
			<div class="page-button <?php echo $options->anchor;?> <?php echo $options->control;?>">
				<ul class="control-button">
					<li class="preview i-back"><span>Prev</span></li>
					<li class="next i-next"><span>Next</span></li>
				</ul>		
			</div>
			<?php }}?>
	
		<div class="slider not-js cols-6 <?php echo $options->deviceclass_sfx; ?>">
			<div class="vpo-wrap">
				<div class="vp">
					<div class="vpi-wrap">
					<?php foreach($list as $item){
					$_product = Mage::getModel('catalog/product')->load($item['id']);
					$now = date("Y-m-d");
					$newsFrom= substr($_product->getData('news_from_date'),0,10);
					$newsTo=  substr($_product->getData('news_to_date'),0,10);
					$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();
					//$isBestProduct =($_product->getResource()->getAttribute('best') AND $_product->getResource()->getAttribute('best')->getFrontend()->getValue($_product)=="Yes")?$_product->getResource()->getAttribute('best')->getFrontend()->getValue($_product):'';
					?>
						<div class="item">
							<?php //if ($specialprice){ ?>
									<!--div class='sale-item'></div>
							<?php //} ?>
							<?php //if ($now>=$newsFrom && $now<=$newsTo){ ?>
									<div class='new-item'></div>
							<?php //} ?>
							<?php //if ($isBestProduct){ ?>
									<div class='best-item'></div-->
							<?php //} ?>
							<div class="item-wrap">
								<?php if( $options->product_title_disp == 1 ){?>
									<div class="item-title">
										<a href="<?php echo $item['link'];?>" <?php echo $smarthelper->getTargetAttr($options->product_links_target);?> onclick="javascript: return true">
											<?php echo $item['title'];?>
										</a>
									</div>
								<?php }?>
								<div class="item-img item-height">
									<div class="item-img-info">
										<span>
											<img src="<?php echo $item['image'];?>" alt="<?php echo $item['title']; ?>" title="<?php echo $item['title']; ?>" />	    				
										</span>
									</div>	
									<?php /*<div class="bg-hover-image"></div>*/?>
									<?php if( $options->product_readmore_disp == 1 ){?>
										<div class="item-read button">
											<a href="<?php echo $item['link'];?>" <?php echo $smarthelper->getTargetAttr($options->product_links_target);?> onclick="javascript: return true";>
												<?php echo $options->product_readmore_text; ?>
											</a>
										</div>	
									<?php }?>										
								</div>																	
								
								<div class="item-info <?php if( $options->theme == "theme2" ){ echo "item-spotlight"; }?> ">
									<div class="item-inner">									
										<div class="item-content">	
										<div class="item-content-small first">
											<?php if( (int)$options->product_price_disp ){ ?>
												<div class="item-price">
													<div class="sale-price">
													<?php echo $item['price'];?>
													</div>
												</div>
											<?php }?>										
											<?php if($_product->isSaleable()){ ?>
												<div class="addcart-slider">
													<a title="<?php echo $this->__('Add to Cart') ?>" href="javascript:void(0);" class="btn-cart bgcolor fontcolor" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
														<span class="icon-shopping-cart"></span>
														<span class="addcart-text">
															<?php echo $this->__('Add to Cart') ?>
														<span>
													</a>
												</div>
												<?php }else{ ?>
													<span class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></span>										
												<?php }?>
											</div>
											<!--div class="item-content-small last">
												<?php //if($options->product_reviews_count == 1){ ?>
												<div class="item-review">
													<?php //echo $item['review']; ?>
												</div>
												<?php //} ?>	
												<div class="actions">
													<ul class="add-to-links">
														<?php //if ($this->helper('wishlist')->isAllow()) : ?>
															<li class="wishlist-slider">
																<!--span class="icon-heart"></span-->
																<!--a href="<?php //echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist">
																	<?php //echo $this->__('Add to Wishlist') ?>
																</a>
															</li>
														<?php //endif; ?>
														<?php //if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
															<li class="compare-slider">
																<!--span class="icon-exchange"></span-->
																<!--a href="<?php //echo $_compareUrl ?>" class="link-compare">
																	<?php //echo $this->__('Add to Compare') ?>
																</a>
															</li>
														<?php //endif; ?>
													</ul>
												</div>
											</div-->
										</div>	
										<?php if( $options->theme == "theme2" ){
											if( $options->product_title_disp == 1 || $options->product_description_disp == 1 || $options->product_readmore_disp == 1 ){?>
											<div class="item-bg"></div>				
										<?php }}?>		
									</div>
								</div>									
							</div>
						</div>
					<?php }?>
					</div>
				</div>
			</div>
		</div>
		
		<?php if($options->anchor !="top"){?>
			<?php if($options->button_display == 1){?>
			<div class="page-button <?php echo $options->anchor;?> <?php echo $options->control;?>">
				<ul class="control-button">
					<li class="preview">Prev</li>
					<li class="next">Next</li>
				</ul>		
			</div>
		<?php }}?>
		
	</div>
	<?php if(!empty($options->posttext)) {  ?>
		<div class="post-text"><?php echo $options->posttext; ?></div>
	<?php } ?>
<?php }else {echo $this->__('Has no item to show!');}?>

<script type="text/javascript">
//<![CDATA[
    jQuery(document).ready(function($){
        $('#<?php echo $uniqued;?> .slider').responsiver({
            interval: <?php echo $options->delay;?>,
            speed: <?php echo $options->duration;?>,
            start: <?php echo $options->start -1;?>,
            step: <?php echo $options->scroll;?>,
            circular: true,
            preload: true,
			fx: 'slide',
            pause: 'hover',
            control:{
				prev: '#<?php echo $uniqued;?> .control-button li[class="preview i-back"]',
				next: '#<?php echo $uniqued;?> .control-button li[class="next i-next"]'
            },
			getColumns: function(element){
				var match = $(element).attr('class').match(/cols-(\d+)/);
				if (match[1]){
					var column = parseInt(match[1]);
				} else {
					var column = 1;
				}
				if (!column) column = 1;
				return column;
			}          
        });
    });
//]]>
</script>



