<?php
    $_productCollection = $this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $imgWidth = $this->product_image_width;
    $imgHeight = $this->product_image_height;
    if ($imgWidth <= 0 || $imgHeight <= 0){
    	$this->product_image_disp = false;
    }
?>

<div class="block">
	<?php if ($this->title): ?>
	<?php 
		$arr_word =  $this->title ? explode(' ',$this->title) : "";
		$join_word = array_shift($arr_word).' <span>'.implode(' ',$arr_word).'</span>';
	 ?>	
	<div class="block-title"><strong><?php echo $join_word; ?></strong></div>
	<?php endif; ?>
    <div class="block-content">
    	<?php if(!$_productCollection->count()): ?>
        	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
        <?php else: 
		$row = 0;
        $col= 0;
        $count = 1;
		foreach($_productCollection as $_product):
			$now = date("Y-m-d");
			$newsFrom= substr($_product->getData('news_from_date'),0,10);
			$newsTo=  substr($_product->getData('news_to_date'),0,10);
			$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
			
            if( ($count==1) || (($count-1)%$this->getNumColumns()== 0) ){
                $row++;
            ?>
            <ul class="products-grid product-menu products cols-<?php echo $this->getNumColumns().' row-'.$row ; ?>">
            <?php
            }?>
                <li class="item <?php echo ( ($count == $_productCollection->count()) || ($count%$this->getNumColumns()==0) )?"last":""; ?>">
                    <div class="item-inner">
                    	<div class="item-box">
							<?php
                            if ($now>=$newsFrom && $now<=$newsTo){
                               // echo "<span class='newproduct-grid'>new</span>";
                                //echo $now.' -- '.$newsFrom.' -- '.$newsTo;
                            }
                            if ($specialprice){
                                //echo "<span class='saleoff-grid'>sale off</span>";
                            }
                            ?>
                            <?php if ($this->product_image_disp): ?>
                            <div class="product-image">
                            	<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgWidth, $imgHeight); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
								<div class="product-menu-info">
									<div class="product-name">
										<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
										<?php
											if ( $this->product_title_max_length > 0){
												$_productNameTruncated = Mage::helper('core/string')->truncate($_productNameStripped, $this->product_title_max_length, "");
											}
										?>
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo isset($_productNameTruncated) ? $_productNameTruncated : $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
									</div>
									<?php if ($this->product_price_disp): ?>
										<?php echo $this->getPriceHtml($_product, true, false) ?>
									<?php endif; ?>	
									<?php if ($this->product_cart_or_status): ?>
									<?php if($_product->isSaleable()): ?>
										<a title="<?php echo $this->__('Add to Cart') ?>" href="javascript:void(0);" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('') ?></span></span></a>
									<?php else: ?>
										<span class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></span>
									<?php endif; ?>
									<?php endif; ?>									
								</div>
                            </div>
                            <?php endif; ?>
							<!--div class="product-box">																		
							</div-->
                        </div>
                          
                	</div>
                </li>
            <?php
			//echo $count.' '.$_productCollection->count().' '.$this->getNumColumns();
			if( ($count == $_productCollection->count()) || ($count%$this->getNumColumns()==0) ){
				?>
				</ul>
				<?php
			}
			$count = $count+1;
			?>
        <?php endforeach; ?>
    <?php endif; ?>
	</div>
</div>
